---
title: "Rmarkdown"
output: html_document
date: "2022-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Funciones auxiliares**
```{R}
library(readxl)

calculateMean<-function(sheet){
  result <-mean(sheet)
  return(result)
}

calculateStandarDeviation<-function(sheet){
  result <- sd(sheet)
  return(result)
}

calculateZValue<-function(confidenceLevel){
  zValue<- qnorm(c(confidenceLevel),mean=0,sd=1,lower.tail=TRUE)
  return(zValue)
}

calculateStandarError<-function(sd,n){
  standarError <- sd/(sqrt(n))
  return(standarError)
}
```

## **Intervalos de confianza**

***objetivo:*** Hallar los intervalos de confianza en duración  para 3 géneros. 

Para la resolución de este objetivo se selecciona los géneros documentales, películas de terror y acción y aventura, además que se escoge un nivel de confianza del 95%.

$$Estimador \pm (confiabilidad\cdot error\_estandar)$$

### ***Código***

```{R}

rutaExcel<-file.choose()

ConfidenceIntervalForTheMean<-function(sheet,confidenceLevel){
  
  n <- length(sheet)
  resultMean <- calculateMean(sheet)
  sd <- calculateStandarDeviation(sheet) 
  cl <- confidenceLevel*100
  z <- calculateZValue(confidenceLevel)
  standarError <- calculateStandarError(sd,n)
  limInf <- resultMean-(z*standarError)
  limSup <- resultMean+(z*standarError)
  
  result <- data.frame(n,resultMean,sd,cl,standarError,limInf,limSup)
  
  return(result)
  
}


```

### Documentales

```{R}
             
documentaries <- read_excel(rutaExcel,sheet = "d118")
ConfidenceIntervalForTheMean(documentaries$Duration,0.95)
```
#### análisis

Con un nivel de confianza del 95% y un error estándar del 2.3 % la duración de los documentales del catálogo de películas de Netflix se encuentra entre 78.77 y 86.45 minutos.




### Terror

```{R}
             
horrorMovies <- read_excel(rutaExcel,sheet = "hM118")
ConfidenceIntervalForTheMean(horrorMovies$Duration,0.95)
```
#### análisis

Con un nivel de confianza del 95% y un error estándar del 2.3 % la duración de las peliculas de terror del catálogo de Netflix se encuentra entre 96.95 y 102.30 minutos.

### Acción y aventura

```{R}
             
actionAndAdventure <- read_excel(rutaExcel,sheet = "AA118")
ConfidenceIntervalForTheMean(actionAndAdventure$Duration,0.95)
```
#### análisis

Con un nivel de confianza del 95% y un error estándar del 1.6 % la duración de las peliculas de terror del catálogo de Netflix se encuentra entre 112.81 y 120.53 minutos.


## Hipotesis de un grupo
A partir de la gran popularidad que ha adquirido  a lo largo de los años Netflix, se asumen que la gran mayoria de sus productos son realmente buenos, es por ello que estos deberían tener una calificación imdbScore alta. Es por ello que Se desea evaluar si el puntaje de las películas del género Documentales del catálogo de Netflix tiene en promedio una aceptación de por lo menos $7.0$; siendo el máximo $10.0$ puntos y el mínimo $1.0$. Con el fin de analizar si al público le gusta el contenido de documentales que ofrece Netflix. 

### ***Código***

```{R}

zTestHaLess<-function(sheet,ls,mu){
  n<-length(sheet)
  xbarra<-calculateMean(sheet)
  sd <- calculateStandarDeviation(sheet) 
  zcal <- (xbarra-mu)/(sd/sqrt(n))
  zval <- calculateZValue(1-ls)*-1
  result <- data.frame(n,xbarra,sd,ls,zcal,zval)
  return(result)
}
```

Hipotesis del caso para el puntaje medio para una significancia del $5%$:

$H_0$: $μ \geq 7.0$ "Los documentale de Netflix tienen buena aceptación en el publico"

$H_a$: $μ <  7.0$ "Los documentale de Netflix No tienen buena aceptación en el publico"

Rechazo $H_0$ si $Z_{cal} \leq Z_{0.0.5}$

$Z_{cal} \leq Z_{0.05}$

$Z_{cal}= \frac{\bar{x}-μ}{\frac{s}{\sqrt{n}}} \leq Z_{0.05}$

```{R}
documentariesForH1 <- read_excel(rutaExcel,sheet = "docuH1")
zTestHaLess(documentariesForH1$Score,0.05,7.0)
```

$$-1.638 \leq -1.644$$
A un nivel de significancia del 5% no hay suficiente evidencia para aceptar $H_0$, por lo tanto, es posible afirmar que en el público de Netflix no tiene buena aceptación hacia el catálogo de documentales de la plataforma.



