---
title: "Rmarkdown"
output: html_document
date: "2022-10-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **Funciones auxiliares**
```{R}
library(readxl)
library(tidyverse)
library(ggplot2)

calculateMean<-function(sheet){
  result <-mean(sheet)
  return(result)
}

calculateStandarDeviation<-function(sheet){
  result <- sd(sheet)
  return(result)
}

calculateZValue<-function(confidenceLevel){
  zValue<- qnorm(c(confidenceLevel),mean=0,sd=1,lower.tail=TRUE)
  return(zValue)
}

calculateStandarError<-function(sd,n){
  standarError <- sd/(sqrt(n))
  return(standarError)
}
```

## **Intervalos de confianza**

***objetivo:*** Hallar los intervalos de confianza de duración promedio para 3 géneros. 

Para la resolución de este objetivo se selecciona los géneros documentales, películas de terror y acción y aventura, además que se escoge un nivel de confianza del 95%.

$$Estimador \pm (confiabilidad\cdot error\_estandar)$$

### ***Código***

```{R}

rutaExcel<-file.choose()

ConfidenceIntervalForTheMean<-function(sheet,confidenceLevel){
  
  n <- length(sheet)
  resultMean <- calculateMean(sheet)
  sd <- calculateStandarDeviation(sheet) 
  cl <- confidenceLevel*100
  z <- calculateZValue(confidenceLevel)
  standarError <- calculateStandarError(sd,n)
  limInf <- resultMean-(z*standarError)
  limSup <- resultMean+(z*standarError)
  
  result <- data.frame(n,resultMean,sd,cl,standarError,limInf,limSup)
  
  return(result)
  
}


```

### Documentales

```{R}
             
documentaries <- read_excel(rutaExcel,sheet = "d118")
ConfidenceIntervalForTheMean(documentaries$Duration,0.95)
```
#### análisis

Con un nivel de confianza del 95% y un error estándar del 2.3 % la duración de los documentales del catálogo de películas de Netflix se encuentra entre 78.77 y 86.45 minutos.




### Terror

```{R}
             
horrorMovies <- read_excel(rutaExcel,sheet = "hM118")
ConfidenceIntervalForTheMean(horrorMovies$Duration,0.95)
```
#### análisis

Con un nivel de confianza del 95% y un error estándar del 1,6 % la duración de las peliculas de terror del catálogo de Netflix se encuentra entre 96.95 y 102.30 minutos.

### Acción y aventura

```{R}
             
actionAndAdventure <- read_excel(rutaExcel,sheet = "AA118")
ConfidenceIntervalForTheMean(actionAndAdventure$Duration,0.95)
```
#### análisis

Con un nivel de confianza del 95% y un error estándar del 2.3 % la duración de las peliculas de terror del catálogo de Netflix se encuentra entre 112.81 y 120.53 minutos.

***Resultados:***

A partir de los resultados obtenidos de los intervalos de confianza, es posible decir que las películas del género de acción y aventura tiene mayor duración que las películas de los géneros documentales y terror.


## Hipotesis de un grupo
A partir de la gran popularidad que ha adquirido  a lo largo de los años Netflix, se asumen que la gran mayoria de sus productos son realmente buenos, es por ello que estos deberían tener una calificación imdbScore alta. Es por ello que Se desea evaluar si el puntaje de las películas del género Documentales del catálogo de Netflix tiene en promedio una aceptación de por lo menos $7.0$; siendo el máximo $10.0$ puntos y el mínimo $1.0$. Con el fin de analizar si al público le gusta el contenido de documentales que ofrece Netflix. 

### ***Código***

```{R}

zTestHaLess<-function(sheet,ls,mu){
  n<-length(sheet)
  xbarra<-calculateMean(sheet)
  sd <- calculateStandarDeviation(sheet) 
  zcal <- (xbarra-mu)/(sd/sqrt(n))
  zval <- calculateZValue(1-ls)*-1
  result <- data.frame(n,xbarra,sd,ls,zcal,zval)
  return(result)
}
```

Hipotesis del caso para el puntaje medio para una significancia del $5%$:

$H_0$: $μ \geq 7.0$ "Los documentale de Netflix tienen buena aceptación en el publico"

$H_a$: $μ <  7.0$ "Los documentale de Netflix No tienen buena aceptación en el publico"

Rechazo $H_0$ si $Z_{cal} \leq Z_{0.0.5}$

$Z_{cal} \leq Z_{0.05}$

$Z_{cal}= \frac{\bar{x}-μ}{\frac{s}{\sqrt{n}}} \leq Z_{0.05}$

```{R}
documentariesForH1 <- read_excel(rutaExcel,sheet = "docuH1")
zTestHaLess(documentariesForH1$Score,0.05,7.0)
```

$$-1.708 \leq -1.644$$
A un nivel de significancia del 5% si hay suficiente evidencia para rechazar $H_0$, por lo tanto, es posible afirmar que los documentales de Netflix No tienen buena aceptación en el publico"

## Hipótesis de dos grupos

***Objetivo: *** Identificar si el puntaje promedio de IMDb de los 2 géneros con mayor contenido son iguales.


Para este caso realizamos una prueba bilateral, en la cual buscamos demostrar que la media de imdb score del género Drama y la media de imdb score del género películas internacionales son diferentes.

**Variables:**
$\mu_1 :$ media imdb score peliculas drama 
$\mu_1 :$ media imdb score peliculas internacionales

**Hipótesis:**

$H_0 : \mu_1 -\mu_2 = 0$ "La media imdb score de las peliculas de drama es igual a la media imdb score de las peliculas internacionales"

$H_a : \mu_1 -\mu_2 \neq 0$ "La media imdb score de las peliculas de drama es diferente a la media imdb score de las peliculas internacionales"

**Resolución:**
Utilizamos la herramienta ggplot para verificar si la media del imdb score de los géneros siguen una distribución normal o aproximadamente normal:

```{R}
dataFrameH2<- read_excel(rutaExcel,sheet = "pruebasH2")

ggplot(dataFrameH2,aes(Score,fill = Genres, color = Genres))+
  geom_density(alpha=0.1)+
  xlim(1,10)

```

En la gráfica es posible observar que los datos siguen una distribución aproximadamente normal.

Utilizamos la gráfica para hacer una análisis grafico de los valores de la media del imdb score de cada muestra de los géneros de Drama y peliculas internacionales:

```{R}
ggplot(dataFrameH2,aes(Genres,Score,fill = Genres, color = Genres))+ 
  geom_boxplot(alpha=0.4)
```

En la diagrama de cajas es posible observar que las medianas del imdb score de los géneros difieren un poco entre si, y tenemos valores atipicos para ambos 
Planteamos las hipotesis para la diferencias de varianzas.

$H_o :\sigma^{2}_{1} = \sigma^{2}_{2}$

$H_a :\sigma^{2}_{1} \neq \sigma^{2}_{2}  $

Rechazamos $H_0:sii VrP<0.05$

Determinamos si las varianzas entre los dos grupos son iguales con la pruebas $var.test()$

```{R}
var.test(Score ~ Genres,data = dataFrameH2)
```

Obtenemos un $VrP = 0.8405$ 

$$0.8405 < 0.05$$

NO

A un nivel de significancia del 5%, NO hay evidencia suficiente para rechazar $H_o$, por lo tanto, las varianzas poblacionales se consideran iguales

Finalmente realizamos la prueba t de student asumiendo que las varianzas son iguales:

Recordemos nuestras hipotesis para la media muestral:

**Hipótesis:**

$H_0 : \mu_1 -\mu_2 = 0$ "La media imdb score de las peliculas de drama es igual a la media imdb score de las peliculas internacionales"

$H_a : \mu_1 -\mu_2 \neq 0$ "La media imdb score de las peliculas de drama es diferente a la media imdb score de las peliculas internacionales"

Usamos la prueba t.test.
```{R}
t.test(Score ~ Genres,data = dataFrameH2,var.equal= T)
```

Rechazamos $H_0:sii VrP<0.05$

$0.1978 < 0.05$

Con un nivel de significancia del 5% NO hay suficiente evidencia para rechazar $H_0$ por lo cual decimos que la media imdb score de las películas de drama es igual a la media imdb score de las peliculas internacionales.