---
title: "PROYECTO INFERENCIA ESTADISTICA-NETFLIX"
output: html_document
date: "Diana Balanta-Danna Espinosa-Cristian Perafan-Geovanny Quintero"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

```
# **Objetivo 04.**


## **Identificar entre 6 géneros cuál tiene el mayor puntaje IMDb score promedio. **

**Generos:** Acción y aventura, niños y peliculas familiares, comedia,documentales,drama, horror.

## **Anova**

**Definición de variables:**

$\mu_1 =$ "score de los productos audiovisuales del género acción y aventura"

$\mu_2 =$ "score de los productos audiovisuales del género niños y peliculas familiares"

$\mu_3 =$ "score de los productos audiovisuales del género comedia"

$\mu_4 =$ "score de los productos audiovisuales del género documentales"

$\mu_5 =$ "score de los productos audiovisuales del género dramas"

$\mu_5 =$ "score de los productos audiovisuales del género peliculas de horror"

**Planteamiento de hipótesis**

$H_0$: $\mu_1 = \mu_2 = \mu_3 = \mu_4 = \mu_5 = \mu_6$ ""No existe diferencia entre la media de los score de los diferentes géneros"

$H_a$: "Por lo menos un par de medias de los scores de los géneros son diferentes"


**Criterio de rechazo:**

Rechazo $H_0$ SII $VrP < \alpha$

**Implementación en R:**

```{R}

library(readxl)
library(rapportools)


rutaExcel <-file.choose()

anovaData <- read_excel(rutaExcel,sheet = "Anova")

attach(anovaData)

anova <- aov(Score~Genres)
summary(anova)


```
**Análisis de resultados: **

Del anterior resumen generado por R podemos obtener $VrP$, evaluamos el $VrP$ en nuestro criterio de rechazo:

$$0.0000062< 0.05$$ 

Con un nivel de significancia de 5%, hay suficiente evidencia para rechazar la HO, por lo tanto existe por lo menos una diferencia entre el score de un par de generos.


**Post Anova**

```{R}
TukeyHSD(anova)

```
**Gráfico de diferencias**
```{R}
plot(TukeyHSD(anova))
```

**Análisis PostAnova**

|Género 1 | Género 2 | Diff    | Conclusión|Media Mayor  |
|-------------|---------------|--------|---------------|--------------------|
|Children & Family|Action & Adventure |-0.636|Action & Adventure> Children & Family |Action & Adventure|
| Comedies  | Action & Adventure | -0.372| Action & Adventure>Comedies|  Action & Adventure |
| Documentaries | Action & Adventure|0.463|Documentaries>Action & Adventure| Documentaries|
|Dramas |Action & Adventure  | -0.27|Action & Adventure> Dramas |Action & Adventure|
|Horror Movies |Action & Adventure  | -1.518|Action & Adventure> Horror Movies|Action & Adventure|
| Comedies|Children & Family|-0.30909091|Children & Family>Comedies| Children & Family|
|Documentaries |Children & Family|0.527|Documentaries> Children & Family|Documentaries|
|Dramas |Children & Family|0.036|Dramas> Children & Family|Dramas|
|Horror Movies|Children & Family|-1.454|Children & Family>Horror Movies| Children & Family|
|Documentaries|Comedies|0.836|Documentaries>Comedies| Documentaries|
|Dramas|Comedies|0.345|Dramas>Comedies| Dramas|
|Horror movies|Comedies|-1.145|Comedies>Horror movies| Comedies|
|Dramas|Documentaries|-0.490|Documentaries>Dramas|Documentaries|
|Horror movies|Documentaries|-1.981|Documentaries>Horror movies|Documentaries|
|Horror movies|Dramas|-1.490|Dramas>Horror movies|Dramas|

Con base a la tabla se deduce entonces que:
*Documentaries>Action & Adventure>Dramas>Children & Family>Comedies>Horror Movies.*

**Concluyendo, se define que las producciones de tipo Documentaries tienen el mayor puntaje IMDb score promedio, mientras que  las de Horror Movies el menor puntaje IMDb promedio.**

**Diagrama de cajas**

```{R}
boxplot(Score~Genres)

```

Los datos coinciden con el diagrama de cajas, ya que se puede observar como la    media del score de Documentaries es la mayor y la media de Horror movies es la menor. También gracias a los intervalos se deduce que la media con mayor diferencia entre todas es la de horror movies, mientras las demás tienen un comportamiento similar.

# **Objetivo 05**


## **Conocer si existe relación entre el género de la película y el continente donde se produjo. (Prueba  de independencia)**

## **Chi-Cuadrado**

Se requiere analizar con un nivel de significancia del 5%, si existe una relacion entre el genero del filme y el continente donde se produjo este. Para ello se agruparon los datos de 3 continentes (Europa, Asia, America) con al menos 6 de los paises de los conforman en cada uno. Obteniendo de este modo la siguiente tabla.

**Importacion de los datos en R:**
```{R}
library(readxl)

##rutaExcel<-file.choose()
##rutaExcel <- "C:/Users/Acer/Documents/GEOVANNY/Universidad/CuartoSemestre/Inferencia Estadistica/projecto/Statistical_Inference_Project/R_project/dataSet/BaseDatosBuena.xlsx"

chiData <- read_excel(rutaExcel,sheet = "ChiCuadrado")
attach(chiData)
Europa <- c(chiData[,2])
Asia <- c(chiData[,3])
America <- c(chiData[,4])

table <- data.frame(Europa,Asia,America)
rownames(table) <- c("Action & Adventure","Anime","Children & Family","Classic Movies","Comedies","Cult Movies","Documentaries","Dramas","Horror","Independent Movies","International Movies","LGBTQ Movies","Music & Musicals","Romantic Movies","Sci-Fi & Fantasy","Stand-Up Comedy","Thrillers","Faith & Spirituality","Sports Movies")
View(table)
print(table)
```

Con ellos es posible plantear las hipotesis que responden a la pregunta: **¿El continente donde se produce un filme, está relacionado con su genero?**

$H_0$: "No hay relacion entre el genero de un filme y el continente donde se produce"

$H_a$: "Hay relacion entre el genero de un filme y el pais continente se produce"

**Criterio de rechazo:**

Rechazo $H_0$ Si $VrP < \alpha$

**Implementacion en R:**
```{R}
chiTest <- chisq.test(table,correct=FALSE)
chiTest
```

**Análisis de resultados: **

Del anterior resumen generado por R se obtiene $VrP$, ahora se evalua $VrP$ en el criterio de rechazo:

$$0.00000000000000022< 0.05$$ 

Con un nivel de significancia de 5%, hay suficiente evidencia para rechazar $H_0$, por lo tanto, hay relacion entre el genero de un filme y el continente que lo produce.

# **Objetivo 06**

## **Establecer el tipo de relación que hay entre la duración de las peliculas y el IMDb Score**

## **Regresión lineal**

Se desea estudiar la relación que existe entre la duración y el score del producto audiovisual en la plataforma Netflix, específicamente para el género horror, para ello se selecciona una muestra de 118 productos audiovisuales del género horror.

**Definición modelo de regresión**

Modelo regresión lineal simple: 
$$\widehat{y} = \beta_0 + \beta_1 x$$
Donde

$\beta_0 :$ "Intercepto de la recta"

$\beta_1 :$ "Pendiente de la recta"

**Definición de variables**

La variable dependendiente es el score y la variable independiente es la duración.

**Implementación en R**
```{R}
library(readxl)
library(QuantPsyc)

regresionData<- read_excel(rutaExcel,sheet = "regresion")

model  = lm(SCORE~DURACION,data = regresionData)

summary(model)
```

**Modelo de estimación**

A partir del dataframe obtenido con ayuda de R, podemos establecer el modelo de estimación:

$\beta_0 = 2.385943$
$\beta_q = 0.028803$


$$\widehat{y} =2.385943 + 0.028803x$$

**Interpretación $\beta_0$**

$B_1= 2.385$

Si no hay un incremento en la duración de las películas el score en promedio sera 2,3.

**Interpretación $\beta_1$**

$B_1=0.028803$

Cuando la duración (en minutos) de las películas del género documental aumenta en una unidad (minutos), el score se incrementa en aproximadamente $0,028803$ en unidad. 

**Interpretación $R^2$**

$R^2=0.1951$

Para $R^2$ tenemos **tres interpretaciones**, nuestra primera interpretación es respecto al porcentaje de $R^2$ y la segunda y tercera es respecto a la siguiente tabla:

**Tabla $R^2$: Para interpretar coeficiente de determinación**

|**Coeficiente**| **Bondad de Ajuste**|**Para estimar**|
|-------------------|-----------------------------|-----------------|
| $R^2$ $\leq$ 0.6|     MALA      |NO ES CONFIABLE PARA HACER ESTIMACIONES |
|0.6 $<$ $R^2$ $\leq$ 0.7| REGULAR| NO ES CONFIABLE PARA HACER ESTIMACIONES|
|0.7 $<$ $R^2$ $\leq$ 0.8| BUENA |ES CONFIABLE PARA HACER ESTIMACIONES|
|0.8 $<$ $R^2$ $\leq$ 0.9| MUY BUENA |ES CONFIABLE PARA HACER ESTIMACIONES|
|0.9 $<$ $R^2$ $\leq$ 1.0 | EXCELENTE |ES CONFIABLE PARA HACER ESTIMACIONES|

**Primera Interpretación**
El modelo propuesto explica el 19.51% de la variabilidad del score que toma las películas del género documental.

**Segunda Interpretación**
El modelo propuesto presenta una bondad de ajuste considerada mala
	
**Tercera Interpretación**
Por lo tanto, este modelo no es confiable para hacer estimaciones.

**Test de correlación**
```{R}
with(regresionData, cor.test(DURACION, SCORE, alternative="two.sided", method="pearson"))
```


**Interpretación $r$**

$r=0.4417563$

Ahora encontramos que el coeficiente de correlación de Pearson  es $0.4417563$. Por lo tanto podemos definir dos interpretaciones:
Como el coeficiente de correlación es positivo decimos que la relación entre Duración y Score IMDb del género horror es directamente proporcional.

La segunda interpretación es respecto a la siguiente tabla:


|**Coeficiente  de correlación ($r$)**| **Relación**|
|----------------------------------------------|-----------------|
| $r$ $\leq$ 0.3|    DEBIL O NULA    |
|0.3 $<$ $r$ $\leq$ 0.5| MODERADA|
|0.5 $<$ $r$ $\leq$ 0.75| FUERTE |
|0.75 $<$ $r$ $\leq$ 1.0| MUY FUERTE|
De la tabla se infiere que la relación entre Duración y Score IMDb es MODERADA ya que el coeficiente de correlación $r=0.4417563$  se encuentra dentro del rango 0.3 $<$ $r$ $\leq$ 0.5 .



**Validación de supuestos**

Para realizar la validación de los supuesto de normalidad y varianza constante (homocedasticidad) primero obtenemos los residuos en R:

```{R}
library(zoo)
library(lmtest)
library(nortest)

residuals<- within(regresionData, {
  residuals.model <- residuals(model) 
})
```
***Normalidad***

Definición de hipótesis:

$H_0 :$ "Los residuos se distribuyen de forma normal"
$H_a :$ "Los residuos NO se distribuyen de formal normal"

Criterio de rechazo:

Rechazo $H_o$ sii $Vrp<\alpha$

Realizamos el Lilliefors (Kolmogorov-Smirnov) normality test:

```{R}
residuos <- residuals(model)

lillie.test(residuos)

```

Del anterior resultado VrP que obtuvimos en R evaluamos en nuestro criterio de rechazo:

$$0.5253 < 0.05$$ 

A un nivel de significancia del 5%  hay suficiente evidencia para rechazar Ho por lo tanto se cumple  que los residuos se comportan de forma normal y se valida el supuesto de normalidad.

***Varianza constante***

Definición de hipótesis:

$H_0 :$ "Los residuos presentan varianza constante (Homocedasticidad)"

$H_a :$ "Los residuos NO presentan varianza constante (Heterocedasticidad)"

Criterio de rechazo:

Rechazo $H_o$ sii $Vrp<\alpha$

Realizamos el Breusch-Pagan test con R e imprimimos resultado :

```{R}
bptest(SCORE ~ DURACION, varformula = ~ fitted.values(model), studentize=FALSE, data=residuals)

```

Evaluamos los resultados: 
$0.6087 < 0.05$

A un nivel de significancia del 5% no hay suficiente evidencia para rechazar Ho por lo tanto se cumple  que los residuos presentan una varianza constante(Homocedasticidad) y se valida el supuesto de homocedasticidad.

***Linealidad***

Definición de hipótesis:

$H_o:$ Los residuos NO se comportan de forma lineal

$H_a:$ Los residuos se comportan de forma lineal

```{R}

fm = aov(lm(SCORE~DURACION,data = regresionData) )

summary(fm)
```
Criterio de rechazo:

Rechazo $H_o$ sii $Vrp<\alpha$

Evaluamos los resultados: 
1.09e-05
$$0.0000109 < 0.05$$
se cumple la desigualdad, por lo tanto, a un nivel de significancia del 5% hay suficiente evidencia para rechazar Ho, es decir que los residuos se comportan de forma lineal y se valida el supuesto de linealidad.


